### ISSUE TITLE
Remote path with spaces cause an exception at populatelstExplorer method

### ISSUE THREAD

**Issue by soerentsch** [andrewiankidd/rcloneExplorer#16]
If had the remote path spaces at the directory name,
the code line `string filePath = temp[11];` can not work.
At the populatelstExplorer method.
At the 
rcloneExplorer/rcloneExplorer/rcloneExplorer.Core.ExploreHandler.cs
class.

**Comment by andrewiankidd** [comment]
I'm not able to reproduce this at all :( Could you check you're not on an old version? please re-open if not
