### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by pedrosimao** [andrewiankidd/rcloneExplorer#17]
Hello,
Can you please post the compiled versions on the releases directory?
I don't have Visual Studio to compile myself.

**Comment by andrewiankidd** [comment]
Hi there,
There is a releases page here:
https://github.com/andrewiankidd/rcloneExplorer/releases/

I don't publish the debug directory as it's often full of rubbish from testing stuff out and the code is hardly ever complete enough to stand up on it's own

Hopefully this is helpful

**Comment by pedrosimao** [comment]
Thanks a lot for that!
