### ISSUE TITLE
[howto request] How to start using this?

### ISSUE THREAD

**Issue by zaggynl** [andrewiankidd/rcloneExplorer#19]
Hi this tool looks awesome but I'm having some difficulties in starting it.
I've downloaded a zip of the project, extracted it and ran the setup.exe to install, all went fine.
On startup of rcloneExplorer it shows a messagebox about a missing .ini file.
On manual creation of the .ini file it shows a messagebox about rclone.exe.
After placing the rclone.exe file in the appropriate folder rcloneExplorer starts but shows nothing: https://i.sli.mg/5dnIIg.jpg (using slimgur as imgur was showing an  error messages at the time)
I'm sure I'm missing something.

**Comment by andrewiankidd** [comment]
Hi, the version in the publish directory is pretty old at this point - I'm surprised it worked at all - I should probably remove that so thanks for reminding me! (sorry!)

Could you try running this version from the releases page?
Thanks

https://github.com/andrewiankidd/rcloneExplorer/releases/download/0.4.2.0a/rcloneExplorer.exe

**Comment by zaggynl** [comment]
Thanks worked, thanks!
