### ISSUE TITLE
Sign key included in source

### ISSUE THREAD

**Issue by zaggynl** [andrewiankidd/rcloneExplorer#20]
Hi, was trying to build this, saw I needed signtool.exe and found rcloneExplorer_TemporaryKey.pfx included, not sure if signing key should be included in github repo.

**Comment by andrewiankidd** [comment]
Hi there - it's just the temporarykey and AFAIK it shouldn't matter if anyone else has access, if a time came were a new key was needed I could just invalidate the existing one and generate a new one, i appreciate the concern though!

there are prebuilt releases in the releases page if you need any :)

https://github.com/andrewiankidd/rcloneExplorer/releases
