### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by djmattyg007** [andrewiankidd/rcloneExplorer#22]
Any chance of a Linux version? This looks amazing.

**Comment by andrewiankidd** [comment]
Def something to look into, I had a test at running it under Mono - but I have a few hardcoded 'exe' related paths which blocks it (my bad). I'll see what I can do

**Comment by andrewiankidd** [comment]
Hiya, I'm not sure if you're aware but someone else has created a cross-platform rclone GUI which seems to trump this

https://github.com/mmozeiko/RcloneBrowser

Hopefully this can help you out!
