### ISSUE TITLE
Add support for encrypted config file

### ISSUE THREAD

**Issue by gyratory** [andrewiankidd/rcloneExplorer#23]
Is it possible to use my old rclone configuration with this program? It has my remotes set up and the entire configuration file has been encrypted with the rclone command.

**Comment by andrewiankidd** [comment]
Hi, this is cos rcloneExplorer is dumb and doesn't know about password-ed config files, as a workaround you can use an unencrypted config file - but I'll see what I can do about adding native support

edit:
As usual, rclone dev has thought of everything, we can set the encryption password as an environment variable before calling rclone process - Implementing now!

**Comment by andrewiankidd** [comment]
I'm going to close this one for now, will be in next release (before xmas hopefully) - for now it's plaintext (yikes) but I'll get that sorted in next version :)

https://github.com/andrewiankidd/rcloneExplorer/commit/7e9f7188718c5070cc274e7fcfc3c248470ac4bb

**Comment by gyratory** [comment]
Alright, thank you for the fast response and feature implementation. I'll look forward to testing the feature in the next version and seeing how it compares against my current solution of mounting the remote on my nas and using midnight commander to transfer/move things around.

**Comment by andrewiankidd** [comment]
https://github.com/andrewiankidd/rcloneExplorer/releases/tag/0.4.2.5

Hopefully you get a notification for this even though it's closed!
