### ISSUE TITLE
Strange Directory Names on OneDrive Connection

### ISSUE THREAD

**Issue by soerentsch** [andrewiankidd/rcloneExplorer#24]
If i make an LSD call with rclone at my OneDrive i get this:
`D:\Projects\rcloneExplorer\rcloneExplorer\bin\Debug>rclone lsd one:`
`          -1 2016-02-26 12:10:41         9 BackUp`
`          -1 2016-12-21 14:05:55        68 Documents`
`          -1 2016-12-02 14:41:34         4 eBooks`
`          -1 2016-10-10 18:48:07         3 Musik`
`          -1 2016-12-22 08:20:57        33 Pictures`
`          -1 2013-09-19 20:56:06         0 Public`
`          -1 2016-04-23 20:55:12         1 Videos`
`2016/12/22 10:54:53
`Transferred:      0 Bytes (0 Bytes/s)
`Errors:                 0`
`Checks:                 0`
`Transferred:            0`
`Elapsed time:       900ms`

But rcloneExplorer show me this Directory names:
`9 BackUp`
`Documents`
`4 eBooks`
`3 Musik`
`Pictures`
`0 Public`
`1 Videos`

Seems that is again an Space-Spliting-Issue ;-)

Anyway, i still love your tool ;-)

**Comment by soerentsch** [comment]
here is my dirty RegEx proposal:
`\s*(-?\d*)\s(\d{4}-\d{2}-\d{2})\s(\d{2}:\d{2}:\d{2})\s*(\d*)\s(.*)`

**Comment by andrewiankidd** [comment]
Regex is def the best way forward, the string splits are a really clumsy way to do it - thanks for the suggestion!

**Comment by andrewiankidd** [comment]
http://andrewiankidd.co.uk/other//rcloneExplorer.exe

Could you try this version if you get a chance? should hopefully fix this issue, but want to check before I go and prep a release

https://github.com/andrewiankidd/rcloneExplorer/commit/46180a38cbf14ed6e9fb24f5495caaa690e42eab

**Comment by andrewiankidd** [comment]
46180a38cbf14ed6e9fb24f5495caaa690e42eab ( and cd0fd014f4ca640fd8d5b4fc7e3bd88cb62cd7d4)
data is now parsed with regex instead of string splits, has worked better in minor testing, but I've made a lot of changes to the internals lately so look forward to some nice new issues appearing 😅 

release created: https://github.com/andrewiankidd/rcloneExplorer/releases/tag/0.4.2.5
