### ISSUE TITLE
Doesn't work with folder / file name in other languages

### ISSUE THREAD

**Issue by jimbb** [andrewiankidd/rcloneExplorer#25]
Hi there,

Trying to play around with this a little bit and it seems that the rcloneExplorer cannot handle folder/file name in Chinese / Japanese at the moment.

1. It is not shown correctly on the interface
2. It skips the folder / files

Thanks!

**Comment by soerentsch** [comment]
This is an Unicode Issue.

Add this lines:
`process.StartInfo.StandardOutputEncoding = Encoding.UTF8;`
`process.StartInfo.StandardErrorEncoding = Encoding.UTF8;`

At the `Execute(...)` methode of the rcloneExplorer.Core.InternalExec class

**Comment by andrewiankidd** [comment]
@soerentsch is correct!
https://github.com/andrewiankidd/rcloneExplorer/commit/3742ba526000c4d92606f651de44826f40b5e1f1
https://i.imgur.com/OTb9S4d.png
